[project]
name = "local-rag-workspace"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "rag-api",
    "rag-embedding",
    "rag-grpc",
    "rag-ingestion",
    "rag-storage",
]

[tool.uv.workspace]
members = [
    "api",
    "ingestion",
    "embedding",
    "llm",
    "packages/*",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "httpx2",
]

[tool.pytest.ini_options]
addopts = "-p no:langsmith"

[tool.uv.sources]
rag-api = { workspace = true }
rag-embedding = { workspace = true }
rag-grpc = { workspace = true }
rag-ingestion = { workspace = true }
rag-llm = { workspace = true }
rag-storage = { workspace = true }
