[project]
name = "rag-ingestion"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "celery[redis]>=5.6.3",
    "langchain-text-splitters",
    "pypdf",
    "rag-core",
    "rag-grpc",
    "rag-storage",
]

[tool.uv.sources]
rag-core = { workspace = true }
rag-grpc = { workspace = true }
rag-storage = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
